### ISSUE TITLE
Crash report: "ERROR RATE LIMITED"

### ISSUE THREAD

**Issue by NavinF** [andrewbanchich/shreddit#18]
```
$ RUST_BACKTRACE=1 SHREDDIT_DRY_RUN=false ./shreddit-linux
<snipped output>
  2023-02-13T03:49:40.904216Z ERROR  RATE LIMITED
    at src/things.rs:238
    in edit with dry_run: false
<snipped output>
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: RateLimited', src/things.rs:298:18
stack backtrace:
   0: rust_begin_unwind
             at /rustc/d5a82bbd26e1ad8b7401f6a718a9c57c96905483/library/std/src/panicking.rs:575:5
   1: core::panicking::panic_fmt
             at /rustc/d5a82bbd26e1ad8b7401f6a718a9c57c96905483/library/core/src/panicking.rs:64:14
   2: core::result::unwrap_failed
             at /rustc/d5a82bbd26e1ad8b7401f6a718a9c57c96905483/library/core/src/result.rs:1791:5
   3: <tracing::instrument::Instrumented<T> as core::future::future::Future>::poll
   4: shreddit::things::Thing::shred::{{closure}}
   5: <core::pin::Pin<P> as core::future::future::Future>::poll
   6: tokio::runtime::scheduler::current_thread::Context::enter
   7: tokio::macros::scoped_tls::ScopedKey<T>::set
   8: tokio::runtime::scheduler::current_thread::CurrentThread::block_on
   9: tokio::runtime::runtime::Runtime::block_on
  10: shreddit::main
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

```
./shreddit-linux --version
shreddit 0.4.2
```

**Comment by NavinF** [comment]
Upon rerunning, it seems to print the same comments over and over after each "DEBUG  Iterating over next page of results" and "INFO  Fetching comments...".

**Comment by NavinF** [comment]
Hmm you probably want to update the README to mention that this tool has the same API limitations as python shreddit and can't delete more than 1000 comments. 

https://github.com/nixfu/reddit-shreddit appears to bypass that limit using the GDPR data dump to locate older comments.

**Comment by andrewbanchich** [comment]
Interesting... It already waits for some time in between requests so that it doesn't hit the rate limit. I'd have thought that if it isn't hitting the rate limit for me then it shouldn't for anyone else.

Are you saying the rate limit error is returned after hitting the 1000 limit of deleted comments?

**Comment by andrewbanchich** [comment]
> https://github.com/nixfu/reddit-shreddit appears to bypass that limit using the GDPR data dump to locate older comments.

I created [a dedicated issue](https://github.com/andrewbanchich/shreddit/issues/24) for this feature as well as one for [adding retry logic](https://github.com/andrewbanchich/shreddit/issues/25).

Are you running more than one instance of `shreddit` or something? I'm not sure why Reddit would rate limit you if there are not other requests being made to your account outside of what `shreddit` is doing.

**Comment by andrewbanchich** [comment]
Closing since I haven't heard anything back.
