### ISSUE TITLE
shreddit 0.4.2 stuck in a (seemingly) endless loop

### ISSUE THREAD

**Issue by nrgetik** [andrewbanchich/shreddit#19]
```
$ shreddit --version
shreddit 0.4.2
```

Running like so, for example:

```
$ shreddit \
    --username "[redacted]" \
    --password "[redacted]" \
    --client-id "[redacted]" \
    --client-secret "[redacted]" \
    --before "2022-12-19 19:06:14.356955841 UTC"
```

Results in a loop of:

```
INFO  Fetching submitted...
DEBUG  Iterating over next page of results
DEBUG  Skipping due to `before` filter
```

Checking on the same posts/comments over and again, seemingly endlessly.

**Comment by andrewbanchich** [comment]
I'm pretty sure I know what the issue is. I'll work on a fix soon. Thanks for the report!

**Comment by andrewbanchich** [comment]
Could you try [`0.4.3`](https://github.com/andrewbanchich/shreddit/releases/tag/v0.4.3) and let me know if that fixes this for you?

**Comment by nrgetik** [comment]
@andrewbanchich it appears to be working again, yep. Thanks!
