### ISSUE TITLE
No releases available

### ISSUE THREAD

**Issue by benjick** [andrewbanchich/shreddit#2]
The docs say the following:

> Download the binary from the [GitHub Releases](https://github.com/andrewbanchich/shreddit/releases) page.

But following that link just tells me there aren't any releases

**Comment by andrewbanchich** [comment]
😅 That's what I get for writing the README before adding the CI stuff. Sorry for the confusion!

I'll try to add that soon. In the meantime, it's possible to install using cargo (although that isn't ideal for users who don't already have that installed).

**Comment by benjick** [comment]
Cheers, that's what I ended up doing 👍

**Comment by andrewbanchich** [comment]
Just added the CI jobs so Linux and Windows builds are available in Releases now. Still need to work on Mac.
