### ISSUE TITLE
"error":403,"message":"Forbidden"

### ISSUE THREAD

**Issue by monster-temp** [andrewbanchich/shreddit#23]
```
  [2m2023-02-26T05:33:16.872246Z[0m [32m INFO[0m  [32mShredding Posts...[0m
    [2;3mat[0m src\cli.rs:52

  [2m2023-02-26T05:33:16.872566Z[0m [32m INFO[0m  [32mFetching Posts...[0m
    [2;3mat[0m src\things.rs:115
    [2;3min[0m [1mlist[0m [2;3mwith[0m [1mthing_type[0m: Posts

  [2m2023-02-26T05:33:17.101877Z[0m [31mERROR[0m  [31m{"error":403,"message":"Forbidden"}:#?[0m
    [2;3mat[0m src\things.rs:164

  [2m2023-02-26T05:33:17.102290Z[0m [34mDEBUG[0m  [34mCompleted listing Posts[0m
    [2;3mat[0m src\cli.rs:67

  [2m2023-02-26T05:33:17.103852Z[0m [32m INFO[0m  [32mShredding Comments...[0m
    [2;3mat[0m src\cli.rs:52

  [2m2023-02-26T05:33:17.104409Z[0m [32m INFO[0m  [32mFetching Comments...[0m
    [2;3mat[0m src\things.rs:115
    [2;3min[0m [1mlist[0m [2;3mwith[0m [1mthing_type[0m: Comments

  [2m2023-02-26T05:33:17.272778Z[0m [31mERROR[0m  [31m{"error":403,"message":"Forbidden"}:#?[0m
    [2;3mat[0m src\things.rs:164

  [2m2023-02-26T05:33:17.273170Z[0m [34mDEBUG[0m  [34mCompleted listing Comments[0m
    [2;3mat[0m src\cli.rs:67
```

**Comment by monster-temp** [comment]
Installing on macos:
`    Updating crates.io index
  Installing shreddit v0.4.3
error: failed to compile `shreddit v0.4.3`, intermediate artifacts can be found at `/var/folders/gz/5tp2y_8538v19y89jcxzrhgw0000gp/T/cargo-installpU5jdN`

Caused by:
  failed to select a version for the requirement `clap = "^4.1.4"`
  candidate versions found which didn't match: 3.2.23, 3.2.22, 3.2.21, ...
  location searched: crates.io index
  required by package `shreddit v0.4.3``
  
  after installing manually (cloning the repo and fixing dependencies) and running i get the same result (the following is macos, initial one was windows)
`  2023-02-26T07:52:53.672958Z  INFO  Shredding Posts...
    at src/cli.rs:52

  2023-02-26T07:52:53.673289Z  INFO  Fetching Posts...
    at src/things.rs:115
    in list with thing_type: Posts

  2023-02-26T07:52:53.936194Z ERROR  {"error":403,"message":"Forbidden"}:#?
    at src/things.rs:164

  2023-02-26T07:52:53.936294Z DEBUG  Completed listing Posts
    at src/cli.rs:67

  2023-02-26T07:52:53.936322Z  INFO  Shredding Comments...
    at src/cli.rs:52

  2023-02-26T07:52:53.936402Z  INFO  Fetching Comments...
    at src/things.rs:115
    in list with thing_type: Comments

  2023-02-26T07:52:54.125871Z ERROR  {"error":403,"message":"Forbidden"}:#?
    at src/things.rs:164

  2023-02-26T07:52:54.126009Z DEBUG  Completed listing Comments
    at src/cli.rs:67
`

**Comment by monster-temp** [comment]
Unfortunately I don't have any rust knowledge to help debug this

**Comment by andrewbanchich** [comment]
There are a couple different things going on here.

First, related to the 403 Forbidden - are you providing your username, password, client secret, and client token correctly? You'll get a 403 if any of that information is incorrect or not provided.

**Comment by andrewbanchich** [comment]
Second, regarding the macOS installation - that is odd. How did you install cargo on macOS? It's saying it could not find the clap 4.0 dependency, which definitely exists. That means your cargo installation is not using an up to date index of crates.

**Comment by andrewbanchich** [comment]
I just tried installing on macOS and it worked fine.

**Comment by monster-temp** [comment]
Okay, it seems that rustup didn't update my cargo for some reason ( i thought it did ), after using cargo to update cargo it installed shreddit fine, but the issue with 403 still remains, and the information is correct (tested with other tools)
My next problem is the following:
`INFO:shreddit:Logged in as meli9525gt.
Traceback (most recent call last):
  File "/Users/miha/opt/miniconda3/bin/shreddit", line 8, in <module>
    sys.exit(main())
  File "/Users/miha/opt/miniconda3/lib/python3.9/site-packages/shreddit/app.py", line 44, in main
    shredder = Shredder(default_config, args.user)
  File "/Users/miha/opt/miniconda3/lib/python3.9/site-packages/shreddit/shredder.py", line 33, in __init__
    self._recent_cutoff = arrow.now().replace(hours=-self._hours)
  File "/Users/miha/opt/miniconda3/lib/python3.9/site-packages/arrow/arrow.py", line 974, in replace
    raise ValueError(f"Unknown attribute: {key!r}.")
ValueError: Unknown attribute: 'hours'.`

**Comment by andrewbanchich** [comment]
> My next problem is the following

Not sure I understand. Those logs are for Python, which this doesn't use in any way.

**Comment by andrewbanchich** [comment]
How are you providing your credentials?

**Comment by monster-temp** [comment]
okay it seems I made a cluster of trying out 100 different things :)
I'm not sure why it's using the python one, but non the less, even not using the shreddit command and just using cargo run, and the .env file, i get the 403

**Comment by andrewbanchich** [comment]
Can you try entering your credentials via the CLI and see if that works?

Also, before doing that, if you run `shreddit --help` it should display in brackets the current env var values for your credentials. Can you look there to confirm they are correct?

**Comment by andrewbanchich** [comment]
Actually, I think I know what's happening. You clones the repo and are running `cargo run`. The repo has an example `shreddit.env` with some fake creds and settings in it. I bet that's what's getting picked up.

**Comment by monster-temp** [comment]
I updated that shreddit.env with my credentials

**Comment by andrewbanchich** [comment]
> I updated that shreddit.env with my credentials

I wonder if one has some characters that aren't being escaped. Did you add some single quotes around the values?

**Comment by monster-temp** [comment]
Yeah I tried with and without using quotes

**Comment by andrewbanchich** [comment]
Does `cargo run -- --help` show the right creds in the output?

**Comment by monster-temp** [comment]
yes it does!

**Comment by andrewbanchich** [comment]
If you go here: https://www.reddit.com/prefs/apps/

And look at the creds you created, what type does it show? "script"?

**Comment by monster-temp** [comment]
yeah, personal use script

**Comment by monster-temp** [comment]
idk if it helps, but this one works perfectly fine with the same credentials 
https://github.com/infinitemh/RedditWiper

**Comment by andrewbanchich** [comment]
Can you:

- Download latest [`0.5.0`](https://github.com/andrewbanchich/shreddit/releases/tag/v0.5.0) release
- Move the binary to the directory with your `shreddit.env` file
- Run `./shreddit` (or `./shreddit.exe` if on Windows)

and see if it works now? Also please let me know what platform you're running on.
