### ISSUE TITLE
thread 'main' panicked again - No such file or directory

### ISSUE THREAD

**Issue by e-m-m-a** [andrewbanchich/shreddit#39]
Credentials are correct, using env. file but same result with command line. Linux on Ubuntu flavour, installed rust then installed as per readme.

emma@pop-os:~$ shreddit 
  2023-04-18T12:23:58.580752Z  INFO  Shredding Posts...
    at /home/emma/.cargo/registry/src/github.com-1ecc6299db9ec823/shreddit-0.7.1/src/main.rs:42

thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Error(Io(Os { code: 2, kind: NotFound, message: "No such file or directory" }))', /home/emma/.cargo/registry/src/github.com-1ecc6299db9ec823/shreddit-0.7.1/src/sources/gdpr.rs:16:39
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

**Comment by andrewbanchich** [comment]
It looks like the path you provided to the GDPR file is not correct. Want to double check that?

**Comment by e-m-m-a** [comment]
I created the folder and its there and correct. However I'm not bothered about an archive and just deleted that line and it ran. Thanks, I loved the old one but this is great too.
