### ISSUE TITLE
its not clear how to use it for non fluent ppl

### ISSUE THREAD

**Issue by drowld** [andrewbanchich/shreddit#40]
I've installed rust in terminal
then ive downloaded your git repo.
But then what should i do ? 
It's not really step by step

**Comment by andrewbanchich** [comment]
Hi! You actually don't need to install Rust for this. You can just download [the latest release](https://github.com/andrewbanchich/shreddit/releases) for your platform, then run the binary. For example, on Linux or Mac, you'd open the terminal, `cd` into the directory with the binary in it, then run `./shreddit`.

**Comment by andrewbanchich** [comment]
Let me know if you have any other questions.
