### ISSUE TITLE
Add LICENSE file in root of git repo

### ISSUE THREAD

**Issue by mutageneral** [andrewbanchich/shreddit#42]
According to "Cargo.toml", this project is licensed under MIT. But no "LICENSE" file is to be found in the root of the git repo. By adding the MIT license to the root of the git repo, it will make the licensing official (currently, it could be argued in court that the program is proprietary) and it will make GitHub show the license in the side panel.

**Comment by andrewbanchich** [comment]
Added. Thanks for pointing this out!
