### ISSUE TITLE
Forgot to use the GPDR folder for 1 post. Now it won't work!!

### ISSUE THREAD

**Issue by mutageneral** [andrewbanchich/shreddit#43]
I ran the command without the GPDR flag because I forgot, then remembered I had it and added the flag and path. Now the program is trying to remove the same comment that has already been deleted in a loop. If the program was better, it would see it is already deleted and skip. Now I can't request another GPDR thing for another 30 days!! Also, this would mean that if you are using GPDR folder feature, and you kill the program for some reason, you can't start it back eider. Big issue IMO.

**Comment by mutageneral** [comment]
I should probably open a separate issue for this but, now I'm running it without the GPDR flag/folder, and it only deletes 25 stuff and then the program quits. No problem for me tho, I'm running it in a simple bash for loop with a 30-second wait in between, trivial: `while true; do ./shreddit-linux --username nop  --password "nop ;)" --client-id nop --client-secret nop ; sleep 30; done`. Hopefully the rate limiting gods won't smite me!

**Comment by mutageneral** [comment]
Ok, so it finished deleting the comments, but it seems it has not touched my posts. Even with `--thing-types posts` it still does not work.

Actually, i just now realize that the huge red wall of text that appears after "INFO Fetching posts..." starts with "ERROR". It seems to be the entire data of every single post in my history. That did not seem to stop it from working for the comments tho... I would be ready to send the error message, but only if I could send it to you directly and privately. It contains all the data I'm trying to delete after all!

**Comment by andrewbanchich** [comment]
I added [a dedicated issue](https://github.com/andrewbanchich/shreddit/issues/49) for this feature. Good idea!

The error due when editing posts was due to Reddit updating their API response and breaking Shreddit. I've release 0.7.2 which includes a fix for this. Let me know if that doesn't solve it for you.
