### ISSUE TITLE
Windows binary immediately closing

### ISSUE THREAD

**Issue by shark-vader** [andrewbanchich/shreddit#45]
I command prompt window opens for a second then closes with no error.

**Comment by andrewbanchich** [comment]
Looks like Reddit updated their API response which broke Shreddit. This should be fixed in [`0.7.2`](https://github.com/andrewbanchich/shreddit/releases/tag/v0.7.2). Can you try that and let me know if it works?

**Comment by andrewbanchich** [comment]
Also, try opening the command prompt first then running Shreddit. Don't right click on Shreddit and run in command prompt directly or else it will, as you described, just close and you won't be able to see the error.
