### ISSUE TITLE
Invalid_grant

### ISSUE THREAD

**Issue by mhluska** [andrewbanchich/shreddit#50]
I get the following error when running `shreddit-mac`:

```
  2023-05-07T21:51:46.790060Z ERROR  {"error":"invalid_grant"}
    at src/main.rs:34

Error: "{\"error\":\"invalid_grant\"}"
```

I have a shreddit.env file that looks like this:

```
SHREDDIT_USERNAME=...
SHREDDIT_PASSWORD=...
SHREDDIT_CLIENT_ID=...
SHREDDIT_CLIENT_SECRET=...
```

Using v0.7.2 Mac binary

**Comment by andrewbanchich** [comment]
Could you provide a bit more information? The logs / config don't show me what operation it was trying to do. Was it deleting comments or posts?

The config should specify that.

**Comment by chrisoffner** [comment]
I get the same just when running
```
./shreddit-mac --username <my_username> --password <my_password> --client-id <my_client_id> --client-secret <my_client_id> --dry-run
```

**Comment by absidue** [comment]
Happens for both types individually a d together.

**Comment by mhluska** [comment]
@andrewbanchich this just happens when I run `$ ./shreddit-mac` with no arguments. I have exported these env variables that its using:

```
SHREDDIT_USERNAME=...
SHREDDIT_PASSWORD=...
SHREDDIT_CLIENT_ID=...
SHREDDIT_CLIENT_SECRET=...
```

**Comment by mhluska** [comment]
I think what could be going on is for the client ID / secret to be valid, users have to [register to use the API](https://www.reddit.com/wiki/api/#wiki_read_the_full_api_terms_and_sign_up_for_usage).

**Comment by andrewbanchich** [comment]
@mhluska @absidue If you navigate here, are there any apps listed under `Developed Applications`?

**Comment by andrewbanchich** [comment]
(sorry, updated with link)

**Comment by stark1tty** [comment]
Turn off 2FA and it should work.

**Comment by andrewbanchich** [comment]
see #58 as well
