### ISSUE TITLE
Exclamation mark ("!") in password needs to be escaped to work

### ISSUE THREAD

**Issue by chrisoffner** [andrewbanchich/shreddit#51]
Running shreddit-mac with a password that includes the sequence `!<digits>` (where `<digits>` is a sequence of digits, like `1234`) gives me the error:

```
zsh: no such event: <digits>
```

Only if I escape the exclamation mark like this: `pAsSwoRd\!<digits>` does it work.

**Comment by andrewbanchich** [comment]
That's just part of ZSH / BASH CLI commands.

https://stackoverflow.com/questions/11025114/how-do-i-escape-an-exclamation-mark-in-bash#11025130
