### ISSUE TITLE
Feature request: Optionally remove successfully deleted comments/posts from CSV so that they don't get processed on re-running

### ISSUE THREAD

**Issue by chrisoffner** [andrewbanchich/shreddit#52]
Maybe it'd be helpful to add an option that removes successfully deleted comments or posts from the respective CSV file so that if the script fails or is cancelled, re-starting it doesn't start going over all the previously deleted things again?

Just a suggestion. :)

**Comment by andrewbanchich** [comment]
Agreed that this would be nice. Existing issue: https://github.com/andrewbanchich/shreddit/issues/49

Planning on adding this when I have some free time.

**Comment by chrisoffner** [comment]
Awesome, thank you! :)
