### ISSUE TITLE
Can't run

### ISSUE THREAD

**Issue by doublearrow** [andrewbanchich/shreddit#53]
Whenever I install from cargo, I get the following errors.

`error: could not compile `futures-core` due to previous error
error: failed to compile `shreddit v0.7.2`, intermediate artifacts can be found at `/var/folders/nx/g122dr4d6bxgj6d770v8rtsw0000gn/T/cargo-installRHLeIz``

I also can't install from the file:

`zsh: permission denied: ./shreddit`

And if I try with sudo:

`sudo: ./shreddit: command not found`

I'm on macOS

**Comment by andrewbanchich** [comment]
Try downloading the binary for the GitHub Releases section and running `./shreddit`.

**Comment by doublearrow** [comment]
Yeah, I just tried that, it's still not working.

**Comment by andrewbanchich** [comment]
What error message do you get when trying to run the binary directly?

**Comment by doublearrow** [comment]
`zsh: permission denied: ./shreddit`

**Comment by andrewbanchich** [comment]
When you download the binary, it should be called `shreddit-mac`. Is `shreddit` just the directory and not the binary?

**Comment by doublearrow** [comment]
Yeah, I renamed the file.

Though now I get `zsh: no such file or directory: ./shreddit`.

**Comment by andrewbanchich** [comment]
Are you running that command in the same directory as the binary? Does `ls` show there is a file called `shreddit`?

**Comment by doublearrow** [comment]
It shows a file called `shreddit-mac`, which is the binary I downloaded.

**Comment by andrewbanchich** [comment]
If the binary is called `shreddit-mac` then you need to run `./shreddit-mac`.

**Comment by doublearrow** [comment]
Tried that - am getting this: `zsh: permission denied: ./shreddit-mac`

**Comment by andrewbanchich** [comment]
Try `chmod +x shreddit-mac` first.

**Comment by doublearrow** [comment]
Thanks so much, it's working now!
