### ISSUE TITLE
Shreddit.env in current directory does nothing

### ISSUE THREAD

**Issue by mhluska** [andrewbanchich/shreddit#54]
When I run `./shreddit-mac` and have a `shreddit.env` file right next to the executable, it doesn't use it for environment variables and I get the command's help output.

If I first do `export $(cat shreddit.env | xargs)` to get the env variables exported, then `./shreddit-mac` works.

**Comment by andrewbanchich** [comment]
Can you try [`0.7.3`](https://github.com/andrewbanchich/shreddit/releases/tag/v0.7.3) and tell me what the first log says?

**Comment by RFBomb** [comment]
for what its worth, I had same issue on windows today. I had a bad setting in my file, so it appeared to just throw it out, and gave me the help output. Resolving the env file allowed it to run
