### ISSUE TITLE
Suggestion: 2 small README tweaks

### ISSUE THREAD

**Issue by Decoherent** [andrewbanchich/shreddit#63]
I'd like to suggest two small tweaks to the README.
1. Although the answer can be found in the Issues section, I think it's worth mentioning that if you have 2FA enabled, you need to append the (current) TOTP code to your password, eg PASSWORD:TOTP. Also, the user better type fast :)

2. I also think that adding a phrase or with the instructions to "create your own app" would help- I don't think it's clear that the "client_id" is the ~22 character alphanumeric ID that's listed under the name of the app that you just created. Pointing that out could avoid some confusion!

Thanks for the tool, really appreciate it :)

**Comment by andrewbanchich** [comment]
Updated the README [here](https://github.com/andrewbanchich/shreddit#create-reddit-app-credentials). Thanks!
