### ISSUE TITLE
Some comments will not be found and edited by this tool. 

### ISSUE THREAD

**Issue by Ataraxic** [andrewbanchich/shreddit#67]
Hello and thanks for writing this little tool. 

I've noticed that it's possible for some comments to appear if you sort by "top" on your own profile instead of new. Probably my old posts were never indexed properly under the new filter or they only bothered to store so many.

Just a heads up for folks.

**Comment by BigEmperor26** [comment]
I noticed that reddit is restoring comments that are deleted recently

**Comment by andrewbanchich** [comment]
Thanks for the info! Yeah, Reddit's APIs do not seem to be extremely well designed or consistent in behavior.

I'd recommend using the GDPR functionality to get the most comprehensive overview of your data.
