### ISSUE TITLE
`invalid_grant` error

### ISSUE THREAD

**Issue by Behinder** [andrewbanchich/shreddit#72]
Does it mean API was shut down one day earlier?

**Comment by andrewbanchich** [comment]
Do you have 2FA enabled?

**Comment by Behinder** [comment]
I never had on any account. Used Power Delete Suite instead

**Comment by andrewbanchich** [comment]
Usually invalid grant errors happen because of incorrect credentials. Can you double check the client ID, client secret, username, and password are all correct?

**Comment by Behinder** [comment]
I dint have any special characters in the passwords. Irrelevant anyway shreddit stopped working

Sebastian Szwarc

**Comment by andrewbanchich** [comment]
@Behinder Shreddit still works. I just tried.

**Comment by akatakritos** [comment]
> This happened for me because I had special characters in the password set in `shreddit.env`. Wrapping it in single quotes fixed it. You should probably do the same (or escape any special characters) when passing the password on the command line.

Thanks for this. My password had a `$` in which was interpreted as a variable interpolation (even in the env file). Single quotes fixed it for me. 

Thanks!

**Comment by haydenk** [comment]
As an alternate solution, because I use a pretty long password with several special characters, I put the password into its own text file names "reddit.pwd".

When I ran shreddit, I just did `shreddit --password $(cat reddit.pwd)`
