### ISSUE TITLE
Main thread panicked

### ISSUE THREAD

**Issue by jamiemarshall-ctf** [andrewbanchich/shreddit#9]

**Comment by jamiemarshall-ctf** [comment]
`thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: reqwest::Error { kind: Decode, source: Error("missing field `access_token`", line: 1, column: 26) }', src\access_token.rs:22:10
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace`

I've created the application and grabbed the secret and client id.

This is with the windows binary version.

What do you think I'm doing wrong? This looks to me like I'm missing the access token but I've put both the client ID and client secret into the terminal.

What could I be missing?

![image](https://user-images.githubusercontent.com/57792776/218059239-5bc6cde7-5b4c-46a2-859b-12a4df7d0237.png)

**Comment by donoftime** [comment]
Did you also set the user and pass? Those are also required to authenticate. 

Here is [a page from the reddit api docs which describes how the oauth flow works](https://github.com/reddit-archive/reddit/wiki/OAuth2-Quick-Start-Example). Essentially, the username, password, client id, and client secret are traded for a short lived access token. That token is then used to authenticate subsequent requests.

**Comment by andrewbanchich** [comment]
Thanks for reporting this @jamiemarshall-ctf . I'm actually getting the same error. That makes me think Reddit changed its API. Looking into this now.

**Comment by andrewbanchich** [comment]
Actually, correction: I am not getting this and Reddit didn't change their API. If you run the program with bad credentials, it currently panics. Good credentials work. So I think @donoftime is probably right - are you providing all the necessary credentials like your username and password?

**Comment by andrewbanchich** [comment]
This is error is surfaced in a more user friendly way in `0.3.2` (about to be released).
