### ISSUE TITLE
[BUG] Username not recognized when username begins with a dash

### ISSUE THREAD

**Issue by jslpc** [andrewbanchich/shreddit#93]
When entering this command (replaced with fake user, pass, client, and secret):

`shreddit --dry-run --replacement-comment "oops" --before "2023-11-01 14:42:43.828192320 UTC" --username "-fakeUsername" --password "Fake*Password29538398257" --client-id 3P8B2cD2fMUl-GqK-3ukaaPQ --client-secret 3zso6CW7ZfsT83Faq2KmwNY3yeM_OaNw`

It results in this error:

```
zsh: no matches found: Fake*Password29538398257
```
I added the quotes because I thought the dash at the start of my username would be a problem, and it was, I think. When removing the quotes, I get this error instead:

```
error: a value is required for '--username <USERNAME>' but none was supplied

For more information, try '--help'.
```

I've also included a `*` in my fake password, as my actual password also has one. Not sure if that's an issue here or not.

**Comment by andrewbanchich** [comment]
Thanks for the report! I think this is a bug in the CLI parsing library I'm using, so I've filed [an issue](https://github.com/clap-rs/clap/issues/5254) there.

**Comment by andrewbanchich** [comment]
this should be fixed in [this release](https://github.com/andrewbanchich/shreddit/releases/tag/v0.9.3). could you confirm please @jslpc ?

**Comment by andrewbanchich** [comment]
Thanks for the report!
