### ISSUE TITLE
Mac binary?

### ISSUE THREAD

**Issue by nhornblower** [andrewbanchich/shreddit#98]
Thanks for rewriting this.

Apparently a dumb question as no one else has asked...

What is the Mac file shreddit-mac? It isn't an .app, doesn't seem to be a .zip or .sit. Not sure what to do with it in Terminal. Any hints?

**Comment by andrewbanchich** [comment]
Hi! If you are in the same directory as the program, just run `./shreddit`. If you add it to your PATH then you can just run `shreddit` from anywhere.

**Comment by muzzah** [comment]
Its not compiled for Apple CPUs is it?

**Comment by andrewbanchich** [comment]
Does the `shreddit-mac` binary not work?

https://github.com/andrewbanchich/shreddit/releases/tag/v0.9.3

I don't have a Mac to test this on so not sure if there's something different needed for their own chips.

**Comment by jlyfshhh** [comment]
The Mac app is not working. It does not recognize it as an app, I can't run ./shreddit.

**Comment by andrewbanchich** [comment]
@jlyfshhh can you provide more details? How are you trying to run it? What error message do you get?

**Comment by jlyfshhh** [comment]
![Screenshot 2024-06-08 at 5 57 57 PM](https://github.com/andrewbanchich/shreddit/assets/57607562/30941d51-dbd7-4769-88d8-46b12aa6fea5)

**Comment by andrewbanchich** [comment]
`chmod +x ./shreddit-mac`

You need to give it executable permissions before running it.

**Comment by jlyfshhh** [comment]
Duh, that was it. It's always the simple things I overlook.

**Comment by andrewbanchich** [comment]
Glad it worked!

Going to close this since I haven't gotten any info about specific errors. If something still isn't working for someone please open a new issue and post details of error.

**Comment by nhornblower** [comment]
Thank you everyone for helping and Andrew for providing the chmod solution. :)
